services:
  eureka-service:
    image: pkay01/ms-eurekaservice:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - micro_java-ms

  config-service:
    image: pkay01/ms-configservice:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - micro_java-ms
    depends_on:
      - eureka-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-service:8761/eureka
    volumes:
      - "c:/Users/StephenAihoon/Desktop/IntLabs/Lab3/micro/git-localconfig-repo:/config-repo"

  user-service:
    image: pkay01/ms-userservice:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - micro_java-ms
    depends_on:
      - eureka-service
      # - config-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-service:8761/eureka

  product-service:
    image: pkay01/ms-productservice:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - micro_java-ms
    depends_on:
      - eureka-service
      # - config-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-service:8761/eureka

  order-service:
    image: pkay01/ms-orderservice:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8083:8083"
    networks:
      - micro_java-ms
    depends_on:
      - eureka-service
      # - config-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-service:8761/eureka

networks:
  micro_java-ms:
    driver: bridge
