spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  cloud:
    config:
      uri: http://config-service:8888
  config:
    activate:
      on-profile: dev
server:
  port: 8083

